<?php

namespace App\Livewire;

use App\Livewire\MRAScalledToday;
use App\Models\Service;
use BezhanSalleh\FilamentShield\Traits\HasWidgetShield;
use Filament\Support\RawJs;
use Filament\Widgets\Concerns\InteractsWithPageFilters;
use Illuminate\Database\Eloquent\Builder;
use Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget;

class GeneratedForcast extends ApexChartWidget
{
    use HasWidgetShield;
    use InteractsWithPageFilters;


    protected static ?string $chartId = 'generatedForcast';
    protected static ?string $heading = 'Generated Forecast';
    protected static ?string $subheading = 'This forecast shows data generated by TMP for planning and performance monitoring.';
    protected static bool $deferLoading = true;


    public static function canView(): bool
    {
        return auth()->user()->can('generate_forecast');
    }

    protected function getOptions(): array
    {
        $startDate = $this->pageFilters['startDate'] ?? null;
        $endDate = $this->pageFilters['endDate'] ?? null;


        return [
            'chart' => [
                'type' => 'pie',
                'height' => 300,
            ],
            'series' => [$this->generatedForecast('Dealer Internal Forecast', $startDate, $endDate), $this->generatedForecast('1. DLR SAP (TMP GENERATED)', $startDate, $endDate)],
            'labels' => ['Dealer Internal Forecast', '1.DLR SAP (TMP GENERATED)'],
            'legend' => [
                'position' => 'bottom',
                'labels' => [
                    'fontFamily' => 'inherit',
                ],
            ],
        ];
    }

    protected function extraJsOptions(): ?RawJs
    {
        return RawJs::make(<<<'JS'
        {
            dataLabels: {
                enabled: true,
                formatter: function (val, opts) {
                    const value = opts.w.config.series[opts.seriesIndex];
                    return value + ' (' + val.toFixed(1) + '%)';
                },
                style: {
                    fontSize: '12px',
                    colors: ['#000']
                },
                background: {
                enabled: true,
                foreColor: '#fff',
                borderRadius: 4,
                opacity: 0.5,
                },
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val;
                    }
                }
            }
        }
        JS);
    }

    public function generatedForecast($source, $startDate, $endDate)
    {
         return Service::query()
            ->whereHas('customer', function ($query) use($source, $startDate, $endDate) {
                $query->where('source', $source);
            })
            ->when($startDate, fn (Builder $query) => $query->whereDate('forecast_date', '>=', $startDate))
            ->when($endDate, fn (Builder $query) => $query->whereDate('forecast_date', '<=', $endDate))
        ->count();
    }
}
